flowchart LR
    evusart_init_to_tx_1_0[WRITE 0x4001380c = 8196, 0ns]
    evusart_init_to_tx_1_1[READ 0x40013800, 150ns]
    evusart_init_to_tx_1_2[/IRQ 0x25, 500ns/]
    evusart_init_to_tx_1_0 -->|150ns| evusart_init_to_tx_1_1
    evusart_init_to_tx_1_1 -->|350ns| evusart_init_to_tx_1_2
    evusart_tx_byte_1_0[WRITE 0x40013804 = 65, 1000ns]
    evusart_tx_byte_1_1[/IRQ 0x25, 1200ns/]
    evusart_tx_byte_1_0 -->|200ns| evusart_tx_byte_1_1
