#!/usr/bin/env python3
"""Machine port driver — PS-X EXE → projeto SaturnRingLib sem passo humano.

Determinístico (tabelas + parsers). Sem IA.
Emite árvore completa pronta para o toolchain SRL; o humano NÃO é o caminho default.

Honesty:
  machine_emits_project = true
  machine_closed_loop   = true   (driver corre end-to-end sozinho)
  game_fidelity_complete = false (cobertura de opcodes GPU/GTE ainda subset)
  runs_on_saturn         = false no núcleo B.A.S.E. (guest runtime ≠ este emit)
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

from emit_from_map import collect_srl_symbols, emit_pad_hpp, load_map  # noqa: E402
from psx_exe import parse_psx_exe, write_minimal_fixture  # noqa: E402

try:
    import yaml
except ImportError as e:  # pragma: no cover
    raise SystemExit("PyYAML required") from e


# GP0 command high-byte → ação SRL (tabela; expandir = mais fidelidade, ainda máquina)
GP0_TABLE = {
    0x00: ("nop", "/* GP0 nop */"),
    0x01: ("clear_cache", "/* GP0 clear cache — no-op on SRL */"),
    0x02: ("fill", "SRL::VDP2::SetBackColor(SRL::Types::HighColor::Colors::Black);"),
    0x20: ("tri_mono", "/* TODO machine: mono triangle → Scene2D/3D */"),
    0x24: ("tri_tex", "/* TODO machine: textured tri → VDP1 */"),
    0x28: ("quad_mono", "/* TODO machine: mono quad → VDP1 */"),
    0x2C: ("quad_tex", "/* TODO machine: textured quad → VDP1 */"),
    0x60: ("rect", "/* TODO machine: rectangle → Scene2D::DrawSprite */"),
    0xA0: ("cpu_to_vram", "/* TODO machine: TIM upload → VDP1::TryLoadTexture */"),
    0xC0: ("vram_to_cpu", "/* TODO machine: VRAM readback unsupported */"),
    0xE1: ("texpage", "/* TODO machine: texpage → CRAM/VDP1 state */"),
    0xE3: ("clip1", "/* TODO machine: drawing area */"),
    0xE4: ("clip2", "/* TODO machine: drawing area */"),
    0xE5: ("offset", "/* TODO machine: draw offset */"),
    0xE6: ("mask", "/* TODO machine: mask bit */"),
}


def srl_root() -> Path:
    link = ROOT / "SaturnRingLib"
    if link.is_dir():
        return link.resolve()
    p = Path("/media/bruno/Bruno/SaturnRingLib")
    if p.is_dir():
        return p
    raise SystemExit("SaturnRingLib missing — scripts/setup.sh")


def decode_mips_inventory(code: bytes, base: int, limit: int = 256) -> list[dict]:
    """Lightweight MIPS word scan — inventory only (not full recomp)."""
    ops = []
    n = min(len(code) // 4, limit)
    for i in range(n):
        w = int.from_bytes(code[i * 4 : i * 4 + 4], "little")
        addr = base + i * 4
        op = (w >> 26) & 0x3F
        fn = w & 0x3F
        kind = "other"
        if w == 0:
            kind = "nop"
        elif op == 0 and fn == 0x08:
            kind = "jr"
        elif op == 0 and fn == 0x09:
            kind = "jalr"
        elif op == 0x02:
            kind = "j"
        elif op == 0x03:
            kind = "jal"
        elif op == 0x09:
            kind = "addiu"
        elif op == 0x0F:
            kind = "lui"
        elif op == 0x0C:
            kind = "syscall"
        ops.append({"addr": hex(addr), "word": hex(w), "kind": kind})
    return ops


def emit_gpu_translate_hxx() -> str:
    lines = [
        "// AUTO-GENERATED by machine_port.py — GP0 → SRL (table-driven)",
        "#pragma once",
        "#include <srl.hpp>",
        "#include <cstdint>",
        "",
        "namespace PsxSaturnBridge {",
        "namespace Gpu {",
        "",
        "inline void TranslateGp0(uint8_t cmd) {",
        "    switch (cmd) {",
    ]
    for cmd, (name, body) in sorted(GP0_TABLE.items()):
        lines.append(f"    case 0x{cmd:02X}: /* {name} */ {body} break;")
    lines += [
        "    default: /* unknown GP0 — machine no-op */ break;",
        "    }",
        "}",
        "",
        "} // namespace Gpu",
        "} // namespace PsxSaturnBridge",
        "",
    ]
    return "\n".join(lines)


def emit_machine_main(exe_meta: dict, symbols: list[str]) -> str:
    sym_c = "\n".join(f"//   - {s}" for s in symbols)
    return f"""\
// AUTO-GENERATED by machine_port.py — caminho máquina (sem humano)
#include <srl.hpp>
#include "psx_pad_map.hpp"
#include "gpu_translate.hpp"

using namespace SRL::Types;
using namespace PsxSaturnBridge;

// Provenance (machine receipt)
// exe: {exe_meta.get('path')}
// pc:  {exe_meta.get('pc_hex')}
// text:{exe_meta.get('text_addr_hex')} size={exe_meta.get('text_size')}
// sha: {exe_meta.get('code_sha256')}
{sym_c}

static void MachineBootBanner()
{{
    SRL::Debug::Print(1, 1, "machine_port: autonomous");
    SRL::Debug::Print(1, 2, "PS1->SRL driver (no human)");
}}

static void MachineTick(SRL::Input::Digital& pad)
{{
    // Input: YAML→PadMap (máquina)
    if (pad.IsConnected() && PadMap::Start(pad))
        SRL::Debug::Print(1, 4, "pad Start");

    // GPU: tabela GP0 (máquina) — alimentar com stream real no próximo incremento
    Gpu::TranslateGp0(0x02);

    // CPU: inventário MIPS no receipt; tradução ISA → SH-2 via base-recomp encode (offline)
}}

int main()
{{
    SRL::Core::Initialize(HighColor::Colors::Black);
    MachineBootBanner();
    SRL::Input::Digital pad(0);

    while (1)
    {{
        MachineTick(pad);
        SRL::Core::Synchronize();
    }}
    return 0;
}}
"""


def emit_makefile(srl: Path, cd_name: str) -> str:
    return f"""\
# AUTO-GENERATED by machine_port.py
SRL_MAX_TEXTURES = 100
SRL_MODE = NTSC
SRL_HIGH_RES = 0
SRL_FRAMERATE = 1
SRL_MAX_CD_BACKGROUND_JOBS = 1
SRL_MAX_CD_FILES = 256
SRL_MAX_CD_RETRIES = 5
SRL_MALLOC_METHOD = TLSF
SRL_USE_SGL_SOUND_DRIVER = 1
SRL_ENABLE_FREQ_ANALYSIS = 0
SGL_MAX_VERTICES = 2500
SGL_MAX_POLYGONS = 1500
SGL_MAX_EVENTS = 1
SGL_MAX_WORKS = 1
CD_NAME = {cd_name}
BUILD_DROP = ./BuildDrop
SRL_INSTALL_ROOT = {srl}
SOURCES = $(patsubst ./%,%,$(shell find src/ -name '*.c' 2>/dev/null))
SOURCES += $(patsubst ./%,%,$(shell find src/ -name '*.cxx' 2>/dev/null))
SDK_ROOT = $(SRL_INSTALL_ROOT)/saturnringlib
include $(SDK_ROOT)/shared.mk
"""


def try_base_recomp_encode(out_dir: Path) -> dict:
    """Call base CLI if built — SH-2 encode smoke (máquina)."""
    repo = ROOT.parents[1]
    base = repo / "target" / "debug" / "base"
    if not base.is_file():
        return {"invoked": False, "reason": "base binary missing"}
    enc_out = out_dir / "recomp_encode"
    enc_out.mkdir(exist_ok=True)
    # nop; ret style isn't MIPS — use known hex that encode accepts for sh2 via SIR path
    # machine records attempt; failure is OK (subset)
    try:
        r = subprocess.run(
            [
                str(base),
                "recomp",
                "encode",
                "--hex",
                "B80100000083C002C3",
                "--target",
                "sh2",
                "-o",
                str(enc_out),
            ],
            capture_output=True,
            text=True,
            timeout=120,
        )
        return {
            "invoked": True,
            "returncode": r.returncode,
            "stdout_tail": (r.stdout or "")[-500:],
            "stderr_tail": (r.stderr or "")[-500:],
            "out": str(enc_out),
        }
    except Exception as e:  # noqa: BLE001
        return {"invoked": True, "error": str(e)}


def machine_port(exe_path: Path, out_root: Path, name: str) -> dict:
    data = load_map(ROOT / "mapping" / "psx_to_srl.yaml")
    symbols = collect_srl_symbols(data)
    exe = parse_psx_exe(exe_path)
    meta = exe.to_dict()
    mips = decode_mips_inventory(exe.code, exe.text_addr)

    proj = out_root / name
    if proj.exists():
        shutil.rmtree(proj)
    src = proj / "src"
    src.mkdir(parents=True)

    (src / "psx_pad_map.hpp").write_text(emit_pad_hpp(data), encoding="utf-8")
    (src / "gpu_translate.hpp").write_text(emit_gpu_translate_hxx(), encoding="utf-8")
    (src / "main.cxx").write_text(emit_machine_main(meta, symbols), encoding="utf-8")
    (proj / "makefile").write_text(emit_makefile(srl_root(), name), encoding="utf-8")

    inventory = {
        "exe": meta,
        "mips_scan": {
            "words_scanned": len(mips),
            "kinds": _count_kinds(mips),
            "sample": mips[:32],
        },
        "gp0_table_coverage": sorted(f"0x{k:02X}" for k in GP0_TABLE),
        "srl_symbols": symbols,
        "subsystems": [
            {"id": s["id"], "strategy": s.get("strategy"), "machine_owned": True}
            for s in data.get("subsystems") or []
        ],
    }
    (proj / "inventory.json").write_text(json.dumps(inventory, indent=2) + "\n", encoding="utf-8")

    recomp = try_base_recomp_encode(proj)

    receipt = {
        "driver": "machine_port",
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "human_required": False,
        "machine_emits_project": True,
        "machine_closed_loop": True,
        "game_fidelity_complete": False,
        "auto_ports_games": False,
        "runs_on_saturn": False,
        "project": str(proj),
        "exe": meta.get("path"),
        "code_sha256": meta.get("code_sha256"),
        "recomp_encode": recomp,
        "next_machine_increments": [
            "expand GP0_TABLE bodies to real VDP1/Scene2D calls",
            "MIPS→SIR→SH-2 lift for leaf functions (base-recomp)",
            "ISO walker → CD file list → SRL::Cd stubs",
            "GTE op table → SRL::Math",
        ],
    }
    (proj / "MACHINE_RECEIPT.json").write_text(json.dumps(receipt, indent=2) + "\n", encoding="utf-8")

    # Also mirror pad emit into shared out/generated for bridge compat
    gen = ROOT / "out" / "generated"
    gen.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src / "psx_pad_map.hpp", gen / "psx_pad_map.hpp")

    return receipt


def _count_kinds(mips: list[dict]) -> dict:
    from collections import Counter

    return dict(Counter(x["kind"] for x in mips))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--exe",
        type=Path,
        default=None,
        help="PS-X EXE path (default: generate fixtures/minimal.exe)",
    )
    ap.add_argument("-o", "--output", type=Path, default=ROOT / "out" / "machine_port")
    ap.add_argument("--name", default="MachinePort")
    args = ap.parse_args()

    if args.exe is None:
        fix = ROOT / "fixtures" / "minimal.exe"
        write_minimal_fixture(fix)
        exe = fix
        print(f"fixture → {fix}")
    else:
        exe = args.exe

    receipt = machine_port(exe, args.output, args.name)
    print(json.dumps({k: receipt[k] for k in (
        "machine_closed_loop",
        "human_required",
        "game_fidelity_complete",
        "project",
        "code_sha256",
    )}, indent=2))
    print(f"OK machine_port → {receipt['project']}")


if __name__ == "__main__":
    main()
