[package]
name = "mycelium-rpc"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "JSON-RPC soberano sobre Mycelium para redes EVM, com política fail-closed e transporte PQC"

[dependencies]
mycelium-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
blake3 = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
mycelium-pqc = { workspace = true }
rand = { workspace = true }
chacha20poly1305 = "0.10"
zeroize = { version = "1.9", features = ["zeroize_derive"] }
