use crate::genome::schema::DeviceGenome;
use serde_yaml;

pub fn to_yaml(genome: &DeviceGenome) -> String {
    serde_yaml::to_string(genome).unwrap_or_else(|_| "error: serialization failed".into())
}

pub fn to_yaml_pretty(genome: &DeviceGenome) -> String {
    let yaml = serde_yaml::to_value(genome).unwrap_or_default();
    serde_yaml::to_string(&yaml).unwrap_or_default()
}

pub fn generate_summary(genomes: &[DeviceGenome]) -> String {
    let mut summary = String::new();
    summary.push_str("# Device Genome Summary\n");
    summary.push_str("# Generated by EAEA Specter Probe\n\n");
    summary.push_str(&format!("total_devices: {}\n", genomes.len()));

    for g in genomes {
        let dt = &g.device.device_type;
        let name = &g.device.name;
        let conf = g.device.confidence;
        summary.push_str(&format!("\n- name: \"{}\"\n", name));
        summary.push_str(&format!("  type: {}\n", dt));
        summary.push_str(&format!("  base: \"0x{:x}\"\n", g.device.base));
        summary.push_str(&format!("  confidence: {:.2}\n", conf));
        summary.push_str(&format!("  registers: {}\n", g.registers.len()));
        summary.push_str(&format!("  polling: {}\n", g.behavior.has_polling));
        summary.push_str(&format!("  state_machine: [{}]\n", g.behavior.state_machine.join(", ")));

        if let Some(ref d) = g.driver {
            summary.push_str(&format!("  driver: {} ({})\n", d.os, d.path));
        }
        if let Some(ref f) = g.firmware {
            summary.push_str(&format!("  firmware: {} ({} bytes)\n", f.name, f.size));
        }
    }

    summary
}
