use crate::behavior::types::{AccessType, DeviceModel};
use std::path::Path;

pub fn generate_device(device: &DeviceModel, output_dir: &Path) -> anyhow::Result<()> {
    let name = device
        .name
        .clone()
        .unwrap_or_else(|| format!("device_{:x}", device.base));
    let dev_dir = output_dir.join("devices").join(&name);
    std::fs::create_dir_all(&dev_dir)?;

    let safe_name = sanitize_c_name(&name);
    let device_type = format!("behavioral-{}", safe_name);
    let state_type = format!("Behavioral{}State", pascal_case(&safe_name));
    let base = device.base;

    generate_header(&dev_dir, &safe_name, &device_type, &state_type, &name, base)?;
    generate_source(&dev_dir, &safe_name, &device_type, &state_type, device)?;
    generate_kconfig(&dev_dir, &safe_name)?;
    generate_meson(&dev_dir, &safe_name)?;
    generate_readme(&dev_dir, &name, device)?;

    tracing::info!("  Generated QEMU device: {}", name);
    Ok(())
}

fn sanitize_c_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>()
        .to_lowercase()
}

fn pascal_case(name: &str) -> String {
    name.split('_')
        .map(|s| {
            let mut chars = s.chars();
            match chars.next() {
                None => String::new(),
                Some(c) => c.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

fn generate_header(
    dir: &Path,
    safe_name: &str,
    device_type: &str,
    state_type: &str,
    _orig_name: &str,
    _base: u64,
) -> anyhow::Result<()> {
    let guard = format!("{}_H", safe_name.to_uppercase());
    let content = format!(
        r#"#ifndef {guard}
#define {guard}

#include "hw/sysbus.h"

#define TYPE_{type_upper} "{device_type}"
OBJECT_DECLARE_SIMPLE_TYPE({state_type}, {type_upper})

typedef struct {state_type} {{
    SysBusDevice parent_obj;

    MemoryRegion mmio;
    qemu_irq irq;

    uint64_t regs[512];
}} {state_type};

#endif
"#,
        guard = guard,
        type_upper = safe_name.to_uppercase(),
        device_type = device_type,
        state_type = state_type,
    );
    std::fs::write(dir.join(format!("{}.h", safe_name)), content)?;
    Ok(())
}

fn generate_source(
    dir: &Path,
    safe_name: &str,
    device_type: &str,
    state_type: &str,
    device: &DeviceModel,
) -> anyhow::Result<()> {
    let base = device.base;
    let reg_defs = generate_c_reg_defs(device);
    let read_switch = generate_c_read_switch(device);
    let write_switch = generate_c_write_switch(device);
    let init_seq = generate_c_init_sequence(device);
    let polling = device.registers.iter().any(|r| r.polling);

    let content = format!(
        r#"#include "qemu/osdep.h"
#include "hw/sysbus.h"
#include "qemu/log.h"
#include "{safe_name}.h"

{reg_defs}

static uint64_t dev_read(void *opaque, hwaddr addr, unsigned size)
{{
    {state_type} *s = {type_upper}(opaque);

    switch (addr) {{
{read_switch}
    default:
        return 0;
    }}
}}

static void dev_write(void *opaque, hwaddr addr, uint64_t val, unsigned size)
{{
    {state_type} *s = {type_upper}(opaque);

    switch (addr) {{
{write_switch}
    default:
        s->regs[addr / 8] = val;
        break;
    }}
}}

static void dev_reset(DeviceState *dev)
{{
    {state_type} *s = {type_upper}(dev);
    memset(s->regs, 0, sizeof(s->regs));
{init_seq}
    if ({polling}) {{
        s->regs[REG_STATUS / 8] = 0x1; /* ready */
    }}
}}

static void dev_realize(DeviceState *dev, Error **errp)
{{
    {state_type} *s = {type_upper}(dev);

    memory_region_init_io(&s->mmio, OBJECT(dev), &dev_ops,
                          s, "{device_type}", 0x1000);
    sysbus_init_mmio(SYS_BUS_DEVICE(dev), &s->mmio);
    sysbus_init_irq(SYS_BUS_DEVICE(dev), &s->irq);
}}

static const MemoryRegionOps dev_ops = {{
    .read = dev_read,
    .write = dev_write,
    .endianness = DEVICE_NATIVE_ENDIAN,
}};

static void dev_class_init(ObjectClass *klass, void *data)
{{
    DeviceClass *dc = DEVICE_CLASS(klass);
    dc->realize = dev_realize;
    dc->reset = dev_reset;
    dc->desc = "Behavioral device at 0x{base:x} (generated by EAEA)";
}}

OBJECT_DEFINE_SIMPLE_TYPE({state_type}, {safe_name},
                          {type_upper}, SYS_BUS_DEVICE)
"#,
        safe_name = safe_name,
        device_type = device_type,
        type_upper = safe_name.to_uppercase(),
        state_type = state_type,
        base = base,
        reg_defs = reg_defs,
        read_switch = read_switch,
        write_switch = write_switch,
        init_seq = init_seq,
        polling = polling,
    );
    std::fs::write(dir.join(format!("{}.c", safe_name)), content)?;
    Ok(())
}

fn generate_c_reg_defs(device: &DeviceModel) -> String {
    let mut lines = String::new();
    for reg in &device.registers {
        let purpose = reg.purpose.as_deref().unwrap_or("reg");
        let name = format!("REG_{:x}", reg.offset);
        lines.push_str(&format!(
            "/* {purpose} register at +0x{offset:x} */\n",
            offset = reg.offset
        ));
        lines.push_str(&format!(
            "#define {name} 0x{offset:x}\n",
            name = name,
            offset = reg.offset,
        ));
    }
    lines
}

fn generate_c_read_switch(device: &DeviceModel) -> String {
    let mut cases = String::new();
    for reg in &device.registers {
        let const_name = format!("REG_{:x}", reg.offset);
        let purpose = reg.purpose.as_deref().unwrap_or("unknown");
        cases.push_str(&format!(
            "    case {const_name}:\n",
            const_name = const_name,
        ));
        if reg.polling {
            cases.push_str(&format!(
                "        /* Polling detected: {count} reads */\n",
                count = reg.count,
            ));
            cases.push_str("        return s->regs[addr / 8] & 0x1;\n");
        } else {
            cases.push_str(&format!(
                "        /* {purpose} */\n",
                purpose = purpose,
            ));
            cases.push_str("        return s->regs[addr / 8];\n");
        }
    }
    cases
}

fn generate_c_write_switch(device: &DeviceModel) -> String {
    let mut cases = String::new();
    for reg in &device.registers {
        if matches!(reg.access, AccessType::Write) {
            let const_name = format!("REG_{:x}", reg.offset);
            let purpose = reg.purpose.as_deref().unwrap_or("unknown");
            cases.push_str(&format!(
                "    case {const_name}:\n",
                const_name = const_name,
            ));
            cases.push_str(&format!(
                "        /* {purpose} write */\n",
                purpose = purpose,
            ));
            cases.push_str("        s->regs[addr / 8] = val;\n");
            cases.push_str("        break;\n");
        }
    }
    cases
}

fn generate_c_init_sequence(device: &DeviceModel) -> String {
    if device.init_sequence.is_empty() {
        return String::new();
    }
    let mut seq = String::new();
    for step in &device.init_sequence {
        seq.push_str(&format!("    /* {step} */\n"));
    }
    seq
}

fn generate_kconfig(dir: &Path, safe_name: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"config BEHAVIORAL_{type_upper}
    bool "Behavioral device {safe_name}"
    depends on ARM
    help
      Behavioral device generated by EAEA Specter Probe.
      Emulates hardware behavior discovered through firmware analysis.
"#,
        type_upper = safe_name.to_uppercase(),
        safe_name = safe_name,
    );
    std::fs::write(dir.join("Kconfig"), content)?;
    Ok(())
}

fn generate_meson(dir: &Path, safe_name: &str) -> anyhow::Result<()> {
    let content = format!(
        r#"# {safe_name} — generated by EAEA Specter Probe
softmmu_ss.add(when: 'CONFIG_BEHAVIORAL_{type_upper}',
               if_true: files('{safe_name}.c'))
"#,
        type_upper = safe_name.to_uppercase(),
        safe_name = safe_name,
    );
    std::fs::write(dir.join("meson.build"), content)?;
    Ok(())
}

fn generate_readme(dir: &Path, name: &str, device: &DeviceModel) -> anyhow::Result<()> {
    let base = device.base;
    let reg_count = device.registers.len();
    let polling = device.registers.iter().filter(|r| r.polling).count();
    let content = format!(
        r#"# {name} — QEMU Behavioral Device

**Generated by EAEA Specter Probe**

## Device Info
- Base address: 0x{base:x}
- Type: {class}
- Confidence: {conf}

## Registers ({reg_count} total)
{polling_note}
## Integration

1. Copy {name}.c and {name}.h to `hw/misc/` in the QEMU source tree
2. Add to `hw/misc/Kconfig`: `source "{name}/Kconfig"`
3. Add to `hw/misc/meson.build`: `subdir('{name}')`
4. Build with `--enable-behavioral-devices`
"#,
        name = name,
        base = base,
        class = device.classification.as_deref().unwrap_or("peripheral"),
        conf = device.confidence,
        reg_count = reg_count,
        polling_note = if polling > 0 {
            format!("- Polling registers: {polling}")
        } else {
            String::new()
        },
    );
    std::fs::write(dir.join("README.md"), content)?;
    Ok(())
}
