// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// AArch64 SIR core: single-cycle, 31x64 GPR, 64-bit PC, NZCV flags.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);

    // State
    reg [63:0] pc;
    reg [63:0] gpr [0:30];
    reg [3:0]  nzcv;

    // Decode
    wire [3:0]  sf     = instr_i[31:28];
    wire [5:0]  opcode = instr_i[30:25];
    wire [1:0]  op2    = instr_i[23:22];
    wire [4:0]  rn     = instr_i[9:5];
    wire [4:0]  rd     = instr_i[4:0];
    wire [11:0] imm12  = instr_i[21:10];

    // Register read (XZR = zero)
    wire [63:0] rn_val = (rn == 5'd31) ? 64'd0 : gpr[rn];
    wire [63:0] rm_val = (rd == 5'd31) ? 64'd0 : gpr[rd];

    // ALU
    reg [63:0] alu_result;
    reg [3:0]  alu_nzcv;
    always @(*) begin
        if (sf == 4'b1001 && opcode == 6'b100100) begin // ADDI (shift=0)
            alu_result = rn_val + {52'b0, imm12};
            alu_nzcv = {alu_result[63], alu_result==0, 1'b0, 1'b0};
        end else if (sf == 4'b1101 && opcode == 6'b100100) begin // SUBI
            alu_result = rn_val - {52'b0, imm12};
            alu_nzcv = {alu_result[63], alu_result==0, 1'b0, 1'b0};
        end else if (sf == 4'b1000 && opcode == 6'b010110) begin // ADD (reg)
            alu_result = rn_val + rm_val;
            alu_nzcv = {alu_result[63], alu_result==0, 1'b0, 1'b0};
        end else if (sf == 4'b1100 && opcode == 6'b010110) begin // SUB (reg)
            alu_result = rn_val - rm_val;
            alu_nzcv = {alu_result[63], alu_result==0, 1'b0, 1'b0};
        end else begin
            alu_result = rn_val;
            alu_nzcv = nzcv;
        end
    end

    // Execute
    always @(posedge clk) begin
        if (rst) begin
            pc <= 64'h0;
            nzcv <= 4'b0;
            for (integer i = 0; i < 31; i = i + 1) gpr[i] <= 64'b0;
        end else begin
            if (rd != 5'd31)
                gpr[rd] <= alu_result;
            nzcv <= alu_nzcv;
            pc <= pc + 4;
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;

endmodule
