// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// DEC Alpha SIR core: 32x64 GPR, no flags (compare-to-register), 64-bit LE.
module MODULE_NAME (
    input  wire        clk, input  wire        rst,
    output wire [63:0] pc_o, input  wire [31:0] instr_i, output wire stall_o
);
    reg [63:0] pc; reg [63:0] gpr [0:31];
    wire [5:0]  opcode = instr_i[31:26];
    wire [4:0]  ra = instr_i[25:21]; wire [4:0] rb = instr_i[20:16];
    wire [4:0]  rc = instr_i[15:11]; wire [5:0] func = instr_i[10:5];
    wire [12:0] mem_disp = instr_i[12:0]; wire [20:0] br_disp = instr_i[20:0];
    wire [63:0] ra_val = gpr[ra]; wire [63:0] rb_val = gpr[rb];
    reg [63:0] alu_result;
    always @(*) begin
        case (opcode)
            6'h08: alu_result = ra_val + {{51{mem_disp[12]}}, mem_disp}; // lda
            6'h0B: alu_result = ra_val + {{51{mem_disp[12]}}, mem_disp}; // ldq
            6'h2B: alu_result = ra_val; // stq
            6'h10: begin // op01 (ALU)
                case (func)
                    6'h20: alu_result = rb_val; // cmpeq (result in rc)
                    6'h2D: alu_result = ra_val + rb_val; // addq
                    6'h3D: alu_result = ra_val - rb_val; // subq
                    default: alu_result = ra_val;
                endcase
            end
            default: alu_result = ra_val;
        endcase
    end
    always @(posedge clk) begin
        if (rst) begin pc <= 64'h0; for (integer i=0; i<32; i=i+1) gpr[i]<=64'b0; end
        else begin
            gpr[rc] <= alu_result;
            pc <= pc + 4;
        end
    end
    assign pc_o = pc; assign stall_o = 1'b0;
endmodule
