// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// ARM (A32) SIR core: single-cycle execute, 16x32 GPR, 32-bit address.
// LE memory model.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [31:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);

    // State
    reg [31:0] pc;
    reg [31:0] gpr [0:15]; // r0..r14 (SP=r13), r15=PC (separate)
    reg [3:0]  cpsr_nzcv;

    // Instruction decode
    wire [3:0]  cond   = instr_i[31:28];
    wire [1:0]  opcode = instr_i[27:26];
    wire        i_bit  = instr_i[25];
    wire [3:0]  op     = instr_i[24:21];
    wire        s_bit  = instr_i[20];
    wire [3:0]  rn     = instr_i[19:16];
    wire [3:0]  rd     = instr_i[15:12];
    wire [7:0]  imm8   = instr_i[7:0];
    wire [3:0]  rm     = instr_i[3:0];

    // Condition evaluation (simplified: only AL)
    wire cond_ok = (cond == 4'hE);

    // ALU inputs
    wire [31:0] op_a = gpr[rn];
    wire [31:0] op_b = i_bit ? {24'b0, imm8} : gpr[rm];

    // ALU
    reg [31:0] alu_result;
    reg [3:0]  alu_nzcv;
    always @(*) begin
        case (op)
            4'hD: begin alu_result = op_a + op_b; alu_nzcv = {op_a[31], (op_a + op_b)==0, 1'b0, 1'b0}; end // ADD
            4'h2: begin alu_result = op_a - op_b; alu_nzcv = {op_a[31], (op_a - op_b)==0, 1'b0, 1'b0}; end // SUB (CMP)
            4'hA: begin alu_result = op_a & op_b; alu_nzcv = {op_a[31], (op_a & op_b)==0, 1'b0, 1'b0}; end // AND
            4'h5: begin alu_result = op_a | op_b; alu_nzcv = {op_a[31], (op_a | op_b)==0, 1'b0, 1'b0}; end // ORR
            4'hC: begin alu_result = op_a | op_b; alu_nzcv = {op_a[31], (op_a | op_b)==0, 1'b0, 1'b0}; end // ORR (MOV)
            default: begin alu_result = op_a; alu_nzcv = cpsr_nzcv; end
        endcase
    end

    // Writeback
    always @(posedge clk) begin
        if (rst) begin
            pc <= 32'h0000_0000;
            cpsr_nzcv <= 4'b0;
            for (integer i = 0; i < 16; i = i + 1) gpr[i] <= 32'b0;
        end else if (cond_ok) begin
            // Write destination (not CMP)
            if (op != 4'h2 && rd != 4'hF)
                gpr[rd] <= alu_result;
            // Update CPSR if S bit
            if (s_bit)
                cpsr_nzcv <= alu_nzcv;
            // PC advance
            if (rd == 4'hF && s_bit)
                pc <= alu_result; // BX LR pattern
            else
                pc <= pc + 4;
        end else begin
            pc <= pc + 4;
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;

endmodule
