// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// ColdFire (M68k) SIR core: D0-D7 + A0-A7, CCR flags, 32-bit BE.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [31:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);
    reg [31:0] pc;
    reg [31:0] dreg [0:7]; // D0-D7 data registers
    reg [31:0] areg [0:7]; // A0-A7 address registers
    reg [4:0]  ccr;        // CCR: X/N/Z/V/C

    wire [15:0] word = instr_i[15:0];
    wire [5:0]  opc_high = instr_i[15:10];
    wire [2:0]  opc_low = instr_i[8:6];
    wire [2:0]  reg_d  = instr_i[2:0];
    wire [2:0]  reg_s  = instr_i[5:3];
    wire [7:0]  imm8   = instr_i[7:0];

    wire [31:0] src_data = dreg[reg_s];
    wire [31:0] dst_data = dreg[reg_d];

    // ALU
    reg [31:0] alu_result;
    reg [4:0]  alu_ccr;
    always @(*) begin
        if (opc_high == 6'hD0 && opc_low == 3'h6) begin // ADD.L Ds,Dd
            alu_result = dst_data + src_data;
            alu_ccr = {1'b0, alu_result[31], alu_result==0, 1'b0, 1'b0};
        end else if (opc_high == 6'h90 && opc_low == 3'h6) begin // SUB.L Ds,Dd
            alu_result = dst_data - src_data;
            alu_ccr = {1'b0, alu_result[31], alu_result==0, 1'b0, 1'b0};
        end else if (opc_high == 6'hB0 && opc_low == 3'h6) begin // CMP.L Ds,Dd
            alu_result = dst_data - src_data;
            alu_ccr = {1'b0, alu_result[31], alu_result==0, 1'b0, 1'b0};
        end else if (opc_high[5:1] == 5'h06) begin // MOVEQ #imm8,Dd
            alu_result = {{24{imm8[7]}}, imm8};
            alu_ccr = ccr;
        end else begin
            alu_result = dst_data;
            alu_ccr = ccr;
        end
    end

    always @(posedge clk) begin
        if (rst) begin
            pc <= 32'h0000_0000;
            ccr <= 5'b0;
            for (integer i = 0; i < 8; i = i + 1) begin
                dreg[i] <= 32'b0;
                areg[i] <= 32'b0;
            end
        end else begin
            if (opc_high[5:1] != 5'h06) // not MOVEQ
                dreg[reg_d] <= alu_result;
            else
                dreg[reg_d] <= alu_result; // MOVEQ also writes
            if (opc_high[5:1] == 5'h16) // CMP.L updates flags
                ccr <= alu_ccr;
            pc <= pc + 2; // ColdFire: variable-length (2/4 bytes)
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;
endmodule
