// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// Intel i860 SIR core: 32x32 GPR, PSR/CC, 32-bit LE.
module MODULE_NAME (
    input  wire        clk, input  wire        rst,
    output wire [31:0] pc_o, input  wire [31:0] instr_i, output wire stall_o
);
    reg [31:0] pc; reg [31:0] gpr [0:31]; reg [7:0] psr; reg [3:0] cc;
    wire [5:0]  opcode = instr_i[31:26]; wire [4:0] rd = instr_i[25:21];
    wire [4:0]  rs1 = instr_i[20:16]; wire [4:0] rs2 = instr_i[15:11];
    reg [31:0] alu_result;
    always @(*) begin
        case (opcode)
            6'h06: alu_result = gpr[rs1] + gpr[rs2]; // add
            6'h0E: alu_result = gpr[rs1] - gpr[rs2]; // sub
            default: alu_result = gpr[rs1];
        endcase
    end
    always @(posedge clk) begin
        if (rst) begin pc <= 32'h0; psr <= 8'b0; cc <= 4'b0;
            for (integer i=0; i<32; i=i+1) gpr[i]<=32'b0;
        end else begin gpr[rd] <= alu_result; pc <= pc + 4; end
    end
    assign pc_o = pc; assign stall_o = 1'b0;
endmodule
