// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// IA-64 (Itanium) SIR core: 128x64 GPR, NaT bits, 64-bit LE.
module MODULE_NAME (
    input  wire        clk, input  wire        rst,
    output wire [63:0] pc_o, input  wire [31:0] instr_i, output wire stall_o
);
    reg [63:0] pc; reg [63:0] gpr [0:127]; reg [127:0] nat;
    wire [4:0]  opcode = instr_i[31:27];
    wire [4:0]  ra_idx = instr_i[9:5]; wire [4:0] rb_idx = instr_i[18:14];
    wire [4:0]  rc_idx = instr_i[4:0];
    reg [63:0] alu_result;
    always @(*) begin
        case (opcode)
            5'h08: alu_result = gpr[{2'b0, ra_idx}] + gpr[{2'b0, rb_idx}];
            5'h09: alu_result = gpr[{2'b0, ra_idx}] - gpr[{2'b0, rb_idx}];
            default: alu_result = gpr[{2'b0, ra_idx}];
        endcase
    end
    always @(posedge clk) begin
        if (rst) begin pc <= 64'h0; nat <= 128'b0;
            for (integer i=0; i<128; i=i+1) gpr[i]<=64'b0;
        end else begin gpr[{2'b0, rc_idx}] <= alu_result; pc <= pc + 4; end
    end
    assign pc_o = pc; assign stall_o = 1'b0;
endmodule
