// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// Motorola 88k SIR core: 32x32 GPR, CR, 32-bit BE.
module MODULE_NAME (
    input  wire        clk, input  wire        rst,
    output wire [31:0] pc_o, input  wire [31:0] instr_i, output wire stall_o
);
    reg [31:0] pc; reg [31:0] gpr [0:31]; reg [3:0] cr;
    wire [5:0]  opcode = instr_i[31:26];
    wire [4:0]  rd = instr_i[25:21]; wire [4:0] rs1 = instr_i[20:16];
    wire [4:0]  rs2 = instr_i[4:0]; wire [4:0] imm5 = instr_i[10:6];
    wire [31:0] src = gpr[rs2];
    reg [31:0] alu_result;
    always @(*) begin
        case (opcode)
            6'h08: alu_result = gpr[rs1] + src; // addu
            6'h10: alu_result = gpr[rs1] - src; // subu
            6'h18: alu_result = (gpr[rs1] < src) ? 32'd1 : 32'd0; // cmpu
            default: alu_result = gpr[rs1];
        endcase
    end
    always @(posedge clk) begin
        if (rst) begin pc <= 32'h0; cr <= 4'b0;
            for (integer i=0; i<32; i=i+1) gpr[i]<=32'b0;
        end else begin gpr[rd] <= alu_result; pc <= pc + 4; end
    end
    assign pc_o = pc; assign stall_o = 1'b0;
endmodule
