// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// MIPS SIR core: single-cycle execute, 32x32 GPR, 32-bit address.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [31:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);

    // State
    reg [31:0] pc;
    reg [31:0] gpr [0:31];
    wire [5:0]  opcode = instr_i[31:26];
    wire [4:0]  rs     = instr_i[25:21];
    wire [4:0]  rt     = instr_i[20:16];
    wire [4:0]  rd     = instr_i[15:11];
    wire [5:0]  funct  = instr_i[5:0];
    wire [15:0] imm16  = instr_i[15:0];
    wire [25:0] jidx   = instr_i[25:0];

    // ALU inputs
    wire [31:0] alu_a = gpr[rs];
    wire [31:0] sext_imm = {{16{imm16[15]}}, imm16};

    // ALU select
    reg [31:0] alu_result;
    always @(*) begin
        case (opcode)
            6'h00: begin // R-type
                case (funct)
                    6'h21: alu_result = alu_a + gpr[rt]; // addu
                    6'h23: alu_result = alu_a - gpr[rt]; // subu
                    6'h2A: alu_result = {31'b0, $signed(alu_a) < $signed(gpr[rt])}; // slt
                    default: alu_result = 32'b0;
                endcase
            end
            6'h08: alu_result = alu_a + sext_imm; // addi
            6'h09: alu_result = alu_a + sext_imm; // addiu
            6'h0A: alu_result = {31'b0, $signed(alu_a) < $signed(sext_imm)}; // slti
            6'h0F: alu_result = {imm16, 16'b0};  // lui
            default: alu_result = 32'b0;
        endcase
    end

    // Memory
    wire [31:0] ld_addr = alu_a + sext_imm;
    reg [31:0] mem [0:255];
    MEM_INIT_BLOCK
    wire [31:0] ld_data = mem[ld_addr[9:2]];

    // Execute
    always @(posedge clk) begin
        if (rst) begin
            pc <= 32'h0000_0000;
            for (integer i = 0; i < 32; i = i + 1)
                gpr[i] <= 32'b0;
        end else begin
            // Writeback
            case (opcode)
                6'h00: begin // R-type
                    case (funct)
                        6'h21: gpr[rd] <= alu_result; // addu
                        6'h23: gpr[rd] <= alu_result; // subu
                        6'h2A: gpr[rd] <= alu_result; // slt
                        6'h08: ; // jr — handled below
                        6'h09: gpr[31] <= pc + 4;    // jalr — link
                        default: ;
                    endcase
                end
                6'h08, 6'h09: gpr[rt] <= alu_result; // addi/addiu
                6'h0A: gpr[rt] <= alu_result;         // slti
                6'h0F: gpr[rt] <= alu_result;         // lui
                6'h23: gpr[rt] <= ld_data;             // lw
                6'h2B: mem[ld_addr[9:2]] <= gpr[rt];  // sw
                6'h03: gpr[31] <= pc + 4;              // jal — link
                default: ;
            endcase

            // PC update (skip for branches/jumps)
            if (opcode == 6'h00 && funct == 6'h08)
                pc <= gpr[rs];          // jr
            else if (opcode == 6'h00 && funct == 6'h09)
                pc <= gpr[rs];          // jalr
            else if (opcode == 6'h03)
                pc <= {pc[31:28], jidx, 2'b00}; // jal
            else
                pc <= pc + 4;
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;

endmodule
