// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// PA-RISC SIR core: 32x32 GPR, nullification, 32-bit BE.
module MODULE_NAME (
    input  wire        clk, input  wire        rst,
    output wire [31:0] pc_o, input  wire [31:0] instr_i, output wire stall_o
);
    reg [31:0] pc; reg [31:0] gpr [0:31];
    wire [5:0]  opcode = instr_i[31:26];
    wire [4:0]  rt = instr_i[21:17]; wire [4:0] ra = instr_i[16:12];
    wire [1:0]  c  = instr_i[13:12];
    wire [4:0]  rb = instr_i[4:0];
    wire [31:0] ra_val = gpr[ra]; wire [31:0] rb_val = gpr[rb];
    reg [31:0] alu_result;
    always @(*) begin
        case (opcode)
            6'h08: alu_result = ra_val + rb_val; // ADD
            6'h0D: alu_result = ra_val + rb_val; // LDO
            default: alu_result = ra_val;
        endcase
    end
    always @(posedge clk) begin
        if (rst) begin pc <= 32'h0; for (integer i=0; i<32; i=i+1) gpr[i]<=32'b0; end
        else begin gpr[rt] <= alu_result; pc <= pc + 4; end
    end
    assign pc_o = pc; assign stall_o = 1'b0;
endmodule
