// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// PowerPC SIR core: 32x32 GPR, CR0, LR, 32-bit BE.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [31:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);
    reg [31:0] pc;
    reg [31:0] gpr [0:31];
    reg [31:0] lr;        // Link Register (r8)
    reg [3:0]  cr0;       // Condition Register: LT/GT/EQ/SO

    wire [5:0]  opcode = instr_i[31:26];
    wire [4:0]  rD     = instr_i[25:21];
    wire [4:0]  rA     = instr_i[20:16];
    wire [4:0]  rB     = instr_i[15:11];
    wire [9:0]  xo     = instr_i[10:1];
    wire        rc     = instr_i[0];
    wire [15:0] imm16  = instr_i[15:0];
    wire [25:0] li      = instr_i[25:0];

    // ALU
    wire [31:0] op_a = gpr[rA];
    wire [31:0] op_b = gpr[rB];
    reg [31:0] alu_result;
    reg [3:0]  alu_cr0;

    always @(*) begin
        case (opcode)
            6'h1F: begin // X-form
                case (xo)
                    10'h214: begin alu_result = op_a + op_b; alu_cr0 = {op_a[31], (op_a+op_b)==0, 1'b0, 1'b0}; end // add
                    10'h218: begin alu_result = op_a - op_b; alu_cr0 = {op_a[31], (op_a-op_b)==0, 1'b0, 1'b0}; end // sub
                    10'h1F0: begin alu_result = $signed(op_a) < $signed(op_b) ? 32'd1 : 32'd0; alu_cr0 = {op_a[31], (op_a==op_b), 1'b0, 1'b0}; end // cmp
                    default: begin alu_result = op_a; alu_cr0 = cr0; end
                endcase
            end
            6'h0E: alu_result = op_a | {16'b0, imm16}; // ori
            6'h0F: alu_result = {imm16, 16'b0};         // lis
            6'h08: alu_result = op_a + {{16{imm16[15]}}, imm16}; // addi
            6'h0C: alu_result = op_a | {16'b0, imm16};  // ori (logical)
            default: alu_result = op_a;
        endcase
    end

    always @(posedge clk) begin
        if (rst) begin
            pc <= 32'h0000_0000;
            lr <= 32'h0;
            cr0 <= 4'b0;
            for (integer i = 0; i < 32; i = i + 1) gpr[i] <= 32'b0;
        end else begin
            case (opcode)
                6'h1F: begin
                    gpr[rD] <= alu_result;
                    if (rc) cr0 <= alu_cr0;
                end
                6'h0E: gpr[rD] <= alu_result; // ori
                6'h0F: gpr[rD] <= alu_result; // lis
                6'h08: gpr[rD] <= alu_result; // addi
                6'h1E: begin // bclr (branch to LR)
                    pc <= lr;
                    lr <= pc + 4;
                end
                6'h12: begin // b (unconditional)
                    if (instr_i[0]) lr <= pc + 4; // bl
                    pc <= {pc[31:28], li, 2'b00};
                end
                6'h13: begin // bc/bclr variants
                    pc <= {pc[31:28], li, 2'b00}; // simplified
                    lr <= pc + 4;
                end
                default: pc <= pc + 4;
            endcase
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;
endmodule
