// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// SPARC SIR core: 32 GPR (flat), icc flags, 32-bit BE.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [31:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);
    reg [31:0] pc;
    reg [31:0] gpr [0:31];
    reg [3:0]  icc; // Z/N/C/V

    wire [5:0]  opcode = instr_i[31:26];
    wire [4:0]  rd     = instr_i[29:25];
    wire [5:0]  op3    = instr_i[24:19];
    wire [4:0]  rs1    = instr_i[18:14];
    wire        i_bit  = instr_i[13];
    wire [4:0]  rs2    = instr_i[4:0];
    wire [12:0] simm13 = instr_i[12:0];

    wire [31:0] src_b = i_bit ? {{19{simm13[12]}}, simm13} : gpr[rs2];
    wire [31:0] alu_a = gpr[rs1];

    reg [31:0] alu_result;
    reg [3:0]  alu_icc;
    always @(*) begin
        if (opcode == 6'h02) begin
            case (op3)
                6'h00: begin alu_result = alu_a + src_b; alu_icc = icc; end // LD
                6'h04: begin alu_result = alu_a + src_b; alu_icc = icc; end // ST
                6'h10: begin // ADDcc
                    alu_result = alu_a + src_b;
                    alu_icc = {alu_result==0, $signed(alu_result) < 0, 1'b0, 1'b0};
                end
                6'h14: begin // SUBcc
                    alu_result = alu_a - src_b;
                    alu_icc = {(alu_a-src_b)==0, $signed(alu_a) < $signed(src_b), 1'b0, 1'b0};
                end
                default: begin alu_result = alu_a + src_b; alu_icc = icc; end
            endcase
        end else if (opcode == 6'h04) begin // ADD imm13
            alu_result = alu_a + src_b;
            alu_icc = icc;
        end else begin
            alu_result = alu_a;
            alu_icc = icc;
        end
    end

    always @(posedge clk) begin
        if (rst) begin
            pc <= 32'h0000_0000;
            icc <= 4'b0;
            for (integer i = 0; i < 32; i = i + 1)
                gpr[i] <= 32'b0;
        end else begin
            if (opcode == 6'h02 && (op3 == 6'h14 || op3 == 6'h10))
                icc <= alu_icc;
            if (rd != 5'd0) gpr[rd] <= alu_result;
            pc <= pc + 4;
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;
endmodule
