// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// SuperH SIR core: 16x32 GPR, T flag, 32-bit LE.
module MODULE_NAME (
    input  wire        clk, input  wire        rst,
    output wire [31:0] pc_o, input  wire [31:0] instr_i, output wire stall_o
);
    reg [31:0] pc; reg [31:0] gpr [0:15]; reg t_flag;
    wire [3:0]  rd = instr_i[11:8]; wire [3:0] rs = instr_i[7:4];
    wire [15:0] imm8 = {{8{instr_i[7]}}, instr_i[7:0]};
    always @(posedge clk) begin
        if (rst) begin pc <= 32'h0; t_flag <= 1'b0;
            for (integer i = 0; i < 16; i = i+1) gpr[i] <= 32'b0;
        end else begin
            gpr[rd] <= gpr[rd] + gpr[rs]; // simplified ADD
            pc <= pc + 2; // SH instructions are 16-bit
        end
    end
    assign pc_o = pc; assign stall_o = 1'b0;
endmodule
