// Auto-generated by B.A.S.E. RTL — MODULE_NAME
// x86-64 SIR core: single-cycle execute, 16x64 GPR, 64-bit PC, subset decoder.

module MODULE_NAME (
    input  wire        clk,
    input  wire        rst,
    output wire [63:0] pc_o,
    input  wire [31:0] instr_i,
    output wire        stall_o
);

    // State
    reg [63:0] pc;
    reg [63:0] gpr [0:15];     // RAX=0, RCX=1, RDX=2, RBX=3, RSP=4, RBP=5, RSI=6, RDI=7, R8-R15=8-15
    reg [3:0]  eflags;         // ZF=0, SF=1, CF=2, OF=3

    // Instruction decode (32-bit subset, no REX prefix in minimal subset)
    wire [7:0]  opcode = instr_i[7:0];
    wire [3:0]  modrm_reg = instr_i[23:20];
    wire [3:0]  modrm_rm  = instr_i[3:0];
    wire [7:0]  modrm = instr_i[15:8];
    wire [31:0] imm32 = instr_i;
    wire [7:0]  imm8  = instr_i[7:0];
    wire [63:0] imm64 = {{32{imm32[31]}}, imm32};
    wire [63:0] sext_imm = {{32{imm32[31]}}, imm32};

    // Register file read
    wire [63:0] ra_val = gpr[modrm_reg];
    wire [63:0] rb_val = gpr[modrm_rm];
    wire [63:0] rc_val = gpr[instr_i[23:20]];

    // EFLAGS
    wire zf = eflags[0];
    wire sf = eflags[1];
    wire cf = eflags[2];
    wire of = eflags[3];

    // ALU
    reg [63:0] alu_result;
    reg [3:0]  alu_eflags;

    always @(*) begin
        case (opcode)
            8'h90: alu_result = 64'b0; // NOP
            8'hC3: alu_result = 64'b0; // RET (handled in PC update)
            8'hB8, 8'hB9, 8'hBA, 8'hBB, 8'hBC, 8'hBD, 8'hBE, 8'hBF: begin // MOV r64, imm64
                alu_result = imm64;
            end
            8'h05: alu_result = gpr[0] + sext_imm; // ADD EAX, imm32
            8'h2D: alu_result = gpr[0] - sext_imm; // SUB EAX, imm32
            8'h83: begin // ADD/SUB r/m32, r32
                case (instr_i[23:21])
                    3'h0: alu_result = ra_val + sext_imm; // ADD r, imm8
                    3'h5: alu_result = ra_val - sext_imm; // SUB r, imm8
                    default: alu_result = ra_val;
                endcase
            end
            8'h81: begin // ADD/SUB/CMP r, imm32
                case (instr_i[23:21])
                    3'h0: alu_result = ra_val + sext_imm; // ADD r, imm32
                    3'h5: alu_result = ra_val - sext_imm; // SUB r, imm32
                    3'h7: alu_result = ra_val - sext_imm; // CMP r, imm32 (flags only)
                    default: alu_result = ra_val;
                endcase
            end
            8'h01: alu_result = ra_val + rb_val; // ADD r/m, r
            8'h29: alu_result = ra_val - rb_val; // SUB r/m, r
            8'h39: alu_result = ra_val - rb_val; // CMP r/m, r
            8'h3B: alu_result = ra_val - rb_val; // CMP r, r/m
            default: alu_result = ra_val;
        endcase

        // Flag updates for arithmetic
        case (opcode)
            8'h05, 8'h2D, 8'h83, 8'h81, 8'h01, 8'h29: begin
                alu_eflags[0] = (alu_result == 64'b0);              // ZF
                alu_eflags[1] = alu_result[63];                     // SF
                alu_eflags[2] = (ra_val[63] & ~alu_result[63]) & (opcode != 8'h2D && opcode != 8'h29); // CF (simplified)
                alu_eflags[3] = (ra_val[63] == sext_imm[63]) && (alu_result[63] != ra_val[63]); // OF
            end
            8'h39, 8'h3B: begin // CMP
                alu_eflags[0] = (alu_result == 64'b0);
                alu_eflags[1] = alu_result[63];
                alu_eflags[2] = (ra_val[63] & ~rb_val[63]) & ~alu_result[63]; // CF for CMP
                alu_eflags[3] = (ra_val[63] == rb_val[63]) && (alu_result[63] != ra_val[63]); // OF
            end
            default: alu_eflags = eflags;
        endcase
    end

    // PC update
    reg [63:0] pc_next;
    always @(*) begin
        case (opcode)
            8'hC3: pc_next = gpr[1];                    // RET
            8'hEB: pc_next = pc + {{56{imm8[7]}}, imm8}; // JMP rel8
            8'hE9: pc_next = pc + {{32{imm32[31]}}, imm32}; // JMP rel32
            8'h0F: begin // Jcc
                case (instr_i[15:8])
                    8'h84: pc_next = zf ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JE rel8
                    8'h85: pc_next = ~zf ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JNE
                    8'h8C: pc_next = cf ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JB/JC
                    8'h8D: pc_next = ~cf ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JAE/JNC
                    8'h8F: pc_next = sf ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JS
                    8'h8E: pc_next = ~sf ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JNS
                    8'h80: pc_next = of ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JO
                    8'h81: pc_next = ~of ? pc + {{56{imm8[7]}}, imm8} : pc + 2; // JNO
                    default: pc_next = pc + 2;
                endcase
            end
            default: pc_next = pc + 1; // Single-byte instructions default
        endcase
    end

    // Execute
    always @(posedge clk) begin
        if (rst) begin
            pc <= 64'h0000_0000;
            eflags <= 4'b0;
            for (integer i = 0; i < 16; i = i + 1) gpr[i] <= 64'b0;
        end else begin
            // Writeback
            case (opcode)
                8'hB8, 8'hB9, 8'hBA, 8'hBB, 8'hBC, 8'hBD, 8'hBE, 8'hBF: // MOV r64, imm64
                    gpr[opcode[3:0]] <= alu_result;
                8'h05: gpr[0] <= alu_result; // ADD EAX, imm32
                8'h2D: gpr[0] <= alu_result; // SUB EAX, imm32
                8'h83: gpr[modrm_reg] <= alu_result; // ADD/SUB r, imm8
                8'h81: gpr[modrm_reg] <= alu_result; // ADD/SUB/CMP r, imm32
                8'h01, 8'h29: gpr[modrm_reg] <= alu_result; // ADD/SUB r/m, r
                default: ;
            endcase

            // EFLAGS update
            if (opcode == 8'h05 || opcode == 8'h2D || opcode == 8'h83 || opcode == 8'h81 || opcode == 8'h01 || opcode == 8'h29)
                eflags <= alu_eflags;
            else if (opcode == 8'h39 || opcode == 8'h3B) // CMP
                eflags <= alu_eflags;

            // PC update
            pc <= pc_next;
        end
    end

    assign pc_o = pc;
    assign stall_o = 1'b0;

endmodule
