[package]
name = "inertia"
description = "CI/CD que viaja pela rede: Vectors executados onde há ATP"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mycelium-core = { workspace = true }
mycelium-ghostid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
hex = { workspace = true }
